### ISSUE TITLE
Error while installing usgs_elevation dataset

### ISSUE THREAD

**Issue by ss-is-master-chief** [ss-is-master-chief/spatial_support#3]
@henrykironde 

When I executed `retriever install postgres usgs-elevation -b -94.98704597353938 39.027001800158615 -94.3599408119917 40.69577051867074` I got the following intermediate result 
```=> Installing usgs-elevation
Creating database usgs_elevation...

Couldn't create database (schema "usgs_elevation" already exists
). Trying to continue anyway.
ERROR: current transaction is aborted, commands ignored until end of transaction block
ERROR: current transaction is aborted, commands ignored until end of transaction block
```
This went on for quite some time. I tried `^C` but it resulted in an infinite loop of  `INSERT 0 1`
```
.
.
.
INSERT 0 1
INSERT 0 1
CREATE INDEX
ANALYZE
COMMIT
Done!
```
I checked for `usgs_elevation` database but `psql -l returned the following`

```
~ $ psql -l
                                   List of databases
   Name    |   Owner   | Encoding |   Collate   |    Ctype    |    Access privileges
-----------+-----------+----------+-------------+-------------+-------------------------
 postgres  | sumitsaha | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | sumitsaha | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/sumitsaha           +
           |           |          |             |             | sumitsaha=CTc/sumitsaha
 template1 | sumitsaha | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/sumitsaha           +
           |           |          |             |             | sumitsaha=CTc/sumitsaha
(3 rows)
```

**Comment by henrykironde** [comment]
Great @ss-is-master-chief. I recommend that you Install PgAdmin (I am using 4 on mac and 3 on windows). Otherwise, you can perform a `drop cascade` on command line. 
Drop the whole `usgs_elevation` database and do it again.
Note, what it is doing is right. When the dataset is present it shows `ERROR: current transaction is aborted, commands ignored until end of transaction block` but that it okey. When do dataset present, It shows shows only 
```cmd
.
.
.
INSERT 0 1
INSERT 0 1
````
Since I used `os.system()`, it inserts the data and throws some output .
I will have to change that part to use subprocess. to run in quiet mode.
